### ISSUE TITLE
ui/ux userlikescreen

### ISSUE THREAD

**Issue by Anissa3005** [nourish-team/nourish-frontend#108]

**Comment by oddpharmacy** [comment]
git fetch origin
git checkout 108-uiux-userlikescreen

**Comment by AmanKumarVlgs** [comment]
Hey can you assign me this @Anissa3005, I'm interested in working on this issue

**Comment by Anissa3005** [comment]
Hi, @AmanKumarVlgs if you want to make contributions, please follow our steps as described in the README file. This way we prevent merge conflicts.

**Comment by AmanKumarVlgs** [comment]
Sure @Anissa3005

**Comment by AmanKumarVlgs** [comment]
Hey @Anissa3005 one more question where I can find your Figma link? I want to contribute as a UI/UX Designer.
