### ISSUE TITLE
weather API

### ISSUE THREAD

**Issue by Anissa3005** [nourish-team/nourish-frontend#11]
Showing on the home page temperature UV and humidity

**Comment by oddpharmacy** [comment]
git fetch origin
git checkout 11-weather-api

**Comment by oddpharmacy** [comment]
To implement data from the Weather API using the user's current location:

- Temperature
- Humidity
- UV Index
- Location (if possible)

**Comment by oddpharmacy** [comment]
Implement it as a box under lorem ipsum in the HomeScreen
