### ISSUE TITLE
 ui/ux add journalscreen

### ISSUE THREAD

**Issue by Anissa3005** [nourish-team/nourish-frontend#118]

**Comment by oddpharmacy** [comment]
git fetch origin
git checkout 118-uiux-add-journalscreen

**Comment by AmanKumarVlgs** [comment]
hey @oddpharmacy are you still working on this?

**Comment by oddpharmacy** [comment]
@AmanKumarVlgs Hello thank you for your interest! Yes, this is an ongoing project and we are still working on it.

**Comment by AmanKumarVlgs** [comment]
thanks for your word @oddpharmacy, can I work with you on this? If you can assign this to me with all the details and the existing Figma link.
